languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
contentDir = "content"

title = "wu的博客"

[params.author]
name = "wu"
image = "img/author.webp"
headline = "知行合一，日拱一卒"
bio = "知行合一，日拱一卒"
links = [
    { email = "mailto:huan@huan666.de" },
    { github = "https://github.com/Huan-zhaojun" },
    { linuxdo = "https://linux.do/u/huan/summary" }
]