[build]
publish = "public"
command = "hugo --gc --minify -b $URL"

[build.environment]
		HUGO_VERSION = "0.148.1"
		HUGO_ENV = "production"
		TZ = "Asia/Shanghai"

[context.production.environment]
		HUGO_ENV = "production"